name: test
on: [push]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.19
        uses: actions/setup-go@v4
        with:
          go-version: 1.19

      - name: Check out code into the Go module directory
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Go mod tidy check
        run: go mod tidy && git diff --exit-code

      - name: Get dependencies
        run: go get -v -t -d ./...

      - name: Execute test
        run: make test