name: test
on: [push]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.22.0
        uses: actions/setup-go@v4
        with:
          go-version: 1.22.0
        
      - name: Check out code into the Go module directory
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Go mod tidy check
        run: go mod tidy && git diff --exit-code

      - name: Get dependencies
        run: go get -v -t -d ./...

      - name: Execute test
        run: make test